name: Hexo Deploy

on:
  push:
    branches:
      - master # 源码分支
  schedule:
    - cron: '0 12 * * *' # 每天自动构建

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: |
        npm ci
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Deploy hexo
      run: |
        hexo clean
        hexo deploy --generate